### ISSUE TITLE
How to make WIG file

### ISSUE THREAD

**Issue by DawnMKing** [eafyounian/Segmentum#1]
I am trying to run your tool, but I am having trouble creating the wig file. I found some command line prompts using samtools online, but they are not outputting in the correct format. What method did you use to convert your bam to wig?

**Comment by eafyounian** [comment]
Hi, thank you for your message! 
Would you please show me the command you are using to create the `WIG` file?
In the README file under the section called "Creating the input files from `BAM` files" there is the command format as well as an example on how to create the wig files from the `BAM` files (i.e. 
`segmentum extract read depth sample_x_t.bam 2000 | gzip -c > sample_x_t.wig.gz`)

**Comment by DawnMKing** [comment]
OH! I completely missed that in the README file... I suppose working late on a Friday night can do that :). I will use the command that you had already provided.

 I was trying to modify a samtools command that I found on biostars:

samtools depth fileName.bam | perl -ne 'BEGIN{ print "track type=print wiggle_0 \
name=fileName description=fileName\n"}; ($c, $start, $depth) = split; \
if ($c ne $lastC) { print "variableStep chrom=$c step=1000\n"; };$lastC=$c; \
next unless $. % 10 ==0;print "$start\t$depth\n" unless $depth<3' > fileName.wig

Thank you for your response!

**Comment by DawnMKing** [comment]
I am also getting errors when I cd into Segmentum-master and run make:
Segmentum-master$ make
mkdir -p bin
ln -sf ../Segmentum.py bin/Segmentum
chmod u+x ./Segmentum.py
gcc -O3 -std=c99 -o compiled/spileup compiled/spileup.c
compiled/spileup.c: In function ‘print_alleles’:
compiled/spileup.c:66: warning: format ‘%d’ expects type ‘int’, but argument 6 has type ‘uint64_t’
compiled/spileup.c: In function ‘main’:
compiled/spileup.c:136: warning: implicit declaration of function ‘getline’
compiled/spileup.c:143: warning: format ‘%d’ expects type ‘int’, but argument 6 has type ‘uint64_t’
compiled/spileup.c:151: warning: format ‘%d’ expects type ‘int’, but argument 6 has type ‘uint64_t’
compiled/spileup.c:153: warning: format ‘%d’ expects type ‘int’, but argument 6 has type ‘uint64_t’
compiled/spileup.c:169: warning: format ‘%d’ expects type ‘int’, but argument 6 has type ‘uint64_t’

**Comment by eafyounian** [comment]
Hi, thank you for you message!

These are just `warnings` and not critical errors. So, for the moment, you can safely ignore them. Segmentum should run properly. I will modify the code to fix for these warnings as soon as possible.

**Comment by DawnMKing** [comment]
I still receive: segmentum: command not found.

I can not get segmentum command to run in terminal. I have followed the steps and included the path in both my .bashrc(export PATH="/pathtodirectory/Segmentum-master/bin:$PATH") and .bash_profile (PATH="/pathtodirecotry/Segmentum-master/bin:$PATH"), which is why I thought maybe the make file was finishing.

**Comment by eafyounian** [comment]
Hi, can you please check whether `Segmentum` works (i.e. Segmentum with capital S). If this does not work would you please let me know what you get if you run the following command when you are in the `Segmentum-master` directory: 
`python3 ./bin/Segmentum`

I just noticed that in the `README `file sometimes I am using `segmentum` and sometimes `Segmentum`. This might have been a source of confusion. I will fix this as soon as possible.

**Comment by DawnMKing** [comment]
That command worked. All of the usage information outputs. Thanks!

**Comment by eafyounian** [comment]
Thank you! Glad to hear that it is now working. So `Segmentum` with capital `S` was the answer?

Please feel free to ask if further question arises.

**Comment by DawnMKing** [comment]
Only the entire command python3 ./bin/Segmentum works. If I only type Segmuntum I get this error:
~$ Segmentum
-bash: /gscuser/dking/gscmnt/gc2737/ding/Data_Processing/SomaticWrapper/Segmentum-master/bin/Segmentum: /bin/env: bad interpreter: No such file or directory

**Comment by eafyounian** [comment]
Thank you for your response!

I see! The problem might be fixed by changing the  first line of the `Segmentum.py` file. Would you please check whether changing `#!/bin/env python` to `#!/usr/bin/env python3` would fix the issue for you (i.e. you should be able to run the tool by writing `Segmentum`).

Thank you in advance for the effort!

**Comment by DawnMKing** [comment]
Yes, that fixed it. I can now run by typing in Segmentum. Thank you!

**Comment by eafyounian** [comment]
Thank you! I will update the code accordingly!
