### ISSUE TITLE
Segmentum analyze error

### ISSUE THREAD

**Issue by DawnMKing** [eafyounian/Segmentum#2]
When I try to run example command on output file:

Segmentum analyze with BAF MMRF_1049_2_T.wig.gz MMRF_1049_2_N.wig.gz B_allele_fraction_2.tsv.gz 11 0.7 0.3

I get the following error:

Traceback (most recent call last):
  File "/gscuser/dking/gscmnt/gc2737/ding/Data_Processing/SomaticWrapper/Segmentum-master/bin/Segmentum", line 963, in <module>
    segmentum_with_baf(int(args['--min_read']), args['<tumor>'], args['<normal>'], args['<BAF_file>'], int(args['<window_size>']), float(args['<clogr_threshold>']), float(args['<BAF_threshold>']), float(args['--logr_merge']), float(args['--baf_merge']), 5, args['--print'], args['--BAF'])
  File "/gscuser/dking/gscmnt/gc2737/ding/Data_Processing/SomaticWrapper/Segmentum-master/bin/Segmentum", line 896, in segmentum_with_baf
    log_ratios = calculate_logratios(read_wig(sample_file), read_wig(ref_file), min_read)
  File "/gscuser/dking/gscmnt/gc2737/ding/Data_Processing/SomaticWrapper/Segmentum-master/bin/Segmentum", line 95, in read_wig
    values.append(float(line))
UnboundLocalError: local variable 'values' referenced before assignment

Am I missing a necessary command?

**Comment by eafyounian** [comment]
I am guessing the content of the `wig` files might be the culprit. Would you please write the `wig` files' first couple of lines here? I am guessing that the files are not starting with `fixedStep`. Thank you in advance!

**Comment by DawnMKing** [comment]
I think I just figure out that when I submit this command to my LSF server:

bsub -M 8000000 -o MMRF_1049_1_T.log -e MMRF_1049_1_T.err -N -u kingdawn@wustl.edu Segmentum extract read depth /gscmnt/gc2737/ding/Original_Data/wxs_tumor/SRR3162946.sorted.reheader.md.newheader.sorted.bam 2000 | gzip -c > /gscuser/dking/gscmnt/gc2737/ding/Data_Processing/SomaticWrapper/Segmentum-master/results/MMRF_1049/MMRF_1049_1_T.wig.gz

That the wig file is actually printing to the err log from my bsub command... the output of the .gz file is just one line saying my job was submitted to queue***.  I have never had my bsub log files get mixed up with my output file before... it is just strange.

Nevertheless, this is likely not a problem with Segmentum and more with my job submission system, maybe...?

I will take those log and err files out and rerun. I am almost sure that should fix this problem.

**Comment by eafyounian** [comment]
Let's hope so! I will be offline for the next 9 hours. I will be able to respond further questions after that.

**Comment by DawnMKing** [comment]
I have re ran everything and checked my files. I get an error with the run with BAF only now:

Input Command:
Segmentum analyze with BAF MMRF_1049_3_T.wig.gz MMRF_1049_1_N.wig.gz  B_allele_fraction_3.tsv.gz 11 0.7 0.3 --min_read=20

Error:
Estimated systematic bias: 0.005.
minimum number of reads required at each location to calculate the coverage log ratio: 20.
Traceback (most recent call last):
  File "/gscuser/dking/gscmnt/gc2737/ding/Data_Processing/SomaticWrapper/Segmentum-master/bin/Segmentum", line 963, in <module>
    segmentum_with_baf(int(args['--min_read']), args['<tumor>'], args['<normal>'], args['<BAF_file>'], int(args['<window_size>']), float(args['<clogr_threshold>']), float(args['<BAF_threshold>']), float(args['--logr_merge']), float(args['--baf_merge']), 5, args['--print'], args['--BAF'])
  File "/gscuser/dking/gscmnt/gc2737/ding/Data_Processing/SomaticWrapper/Segmentum-master/bin/Segmentum", line 907, in segmentum_with_baf
    allele_fractions = extract_sample(snp_file, sample_file_name)
  File "/gscuser/dking/gscmnt/gc2737/ding/Data_Processing/SomaticWrapper/Segmentum-master/bin/Segmentum", line 159, in extract_sample
    values.append( float(lst[sampleIdx]) )

**Comment by DawnMKing** [comment]
This is what my B_allele_fraction_3.tsv.gz file looks like:

CHROM   POSITION    REF ALT SRR3162946.sorted.reheader.md.newheader.sorted
1   14930   A   G   0.00
1   233473  C   G   0.41
1   762005  G   A   0.46
1   762022  T   C   0.44
1   762273  G   A   0.22
1   762320  C   T   0.32
1   777237  C   A   0.42
1   777318  C   T   0.22
1   777361  T   C   0.37
1   783175  G   A   0.43
1   792254  CAA C   0.25
1   792263  A   G   0.71
1   879481  G   C   0.39
1   886492  C   T   0.58
1   886788  G   A   0.33
1   886817  C   T   0.27
1   887560  A   C   0.47
1   889158  G   C   0.39
1   889159  A   C   0.35
1   889638  G   C   0.79
1   892471  G   A   0.48
1   894573  G   A   0.53
1   897325  G   C   0.49
...

**Comment by eafyounian** [comment]
Hi, thank you for your comment!

The error is most probably due to the naming of the sample. In the header of `B_allele_fraction_3.tsv.gz`, the sample name is `SRR3162946.sorted.reheader.md.newheader.sorted` while the tool is looking for the name `MMRF_1049_3_T`. Modifying this should fix the problem. 

Segmentum is written in a way that it takes the name assigned to the `tumor sample` (i.e. when running `Segmentum analyze with BAF ...`) and look for that name in the file containing the B-allele fractions in order to use the content of the column having that name as for the allele fractions.

**Comment by DawnMKing** [comment]
I get a new error now:
Segmentum analyze with BAF MMRF_1049_1_T.wig.gz MMRF_1049_1_N.wig.gz B_allele_fraction_1.tsv.gz 11 0.7 0.3 --min_read=20
Estimated systematic bias: -0.564.
minimum number of reads required at each location to calculate the coverage log ratio: 20.
Traceback (most recent call last):
  File "/gscuser/dking/gscmnt/gc2737/ding/Data_Processing/SomaticWrapper/Segmentum-master/bin/Segmentum", line 963, in <module>
    segmentum_with_baf(int(args['--min_read']), args['<tumor>'], args['<normal>'], args['<BAF_file>'], int(args['<window_size>']), float(args['<clogr_threshold>']), float(args['<BAF_threshold>']), float(args['--logr_merge']), float(args['--baf_merge']), 5, args['--print'], args['--BAF'])
  File "/gscuser/dking/gscmnt/gc2737/ding/Data_Processing/SomaticWrapper/Segmentum-master/bin/Segmentum", line 907, in segmentum_with_baf
    allele_fractions = extract_sample(snp_file, sample_file_name)
  File "/gscuser/dking/gscmnt/gc2737/ding/Data_Processing/SomaticWrapper/Segmentum-master/bin/Segmentum", line 159, in extract_sample
    values.append( float(lst[sampleIdx]) )
ValueError: could not convert string to float: 'G'


Beginning of B_allele file looks like this now:
CHROM   POSITION    REF ALT MMRF_1049_1_T
1   14930   A   G   0.00
1   233473  C   G   0.41
1   762005  G   A   0.46
1   762022  T   C   0.44
1   762273  G   A   0.22
1   762320  C   T   0.32
1   777237  C   A   0.42

**Comment by eafyounian** [comment]
This is a bit harder to guess what is happening. Would you please explain how you changed the header? Would you please also check whether there is a `tab` or some spaces between last two columns in the header as well as lets say the first line after the header?

**Comment by DawnMKing** [comment]
I manually changed the header. Because of the way our directories are ordered by patient and bams by sample, I can not modify the inputs as is. 
However, I did figure out that I needed to type control v and then tab to be able to input the tab character into the file. 
Once I did that the command finished :)
Thank you for all of your help!

**Comment by eafyounian** [comment]
Thank you! Glad to hear that the command finished running!
 
At the latest next week (at the moment I am busy with dream challenge competition with deadline at the end of this week), I will update the code in a way that there is no need for changing the header (i.e. the tool does not check for a specific sample name). The reason that the tool looks in the BAF file for a specific sample name is that in earlier versions of the tool there was a possibility to calculate the `BAF` for many samples at once and save them in one file. Since this is not the case anymore, there is no need to check for the sample name.    

Please feel free to ask if you have more questions.

**Comment by DawnMKing** [comment]
I think I have one final question. I need the cnLOH regions, but when I run this command. I get an empty file with just a header. I noticed that in my .seg file the baf.mean column has a majority of nan values, file below. Is this normal and does this mean there are no cnLOH regions detected in this sample?
'ID chrom   loc.start   loc.end num_probes  seg.mean    baf.mean
MMRF_1049_1_T   1   1000    9000    8   nan nan
MMRF_1049_1_T   1   9000    20000   11  0.4397  0.0400
MMRF_1049_1_T   1   20000   62000   42  -0.8384 nan
MMRF_1049_1_T   1   62000   78000   16  0.6198  nan
MMRF_1049_1_T   1   78000   101000  23  -0.1203 nan
MMRF_1049_1_T   1   101000  231000  130 0.5699  nan
MMRF_1049_1_T   1   231000  560000  329 0.2785  0.2404
MMRF_1049_1_T   1   560000  575000  15  2.4548  nan
MMRF_1049_1_T   1   575000  604000  29  1.8951  nan
MMRF_1049_1_T   1   604000  665000  61  -0.2733 nan
MMRF_1049_1_T   1   665000  702000  37  -0.8112 nan
MMRF_1049_1_T   1   702000  714000  12  0.4155  nan
MMRF_1049_1_T   1   714000  4021000 3307    -0.0520 0.0466
MMRF_1049_1_T   1   4021000 4353000 332 -0.2172 0.0660
MMRF_1049_1_T   1   4353000 4902000 549 -0.0616 0.0633
MMRF_1049_1_T   1   4902000 4925000 23  -0.6938 nan
MMRF_1049_1_T   1   4925000 5045000 120 -0.2201 nan
MMRF_1049_1_T   1   5045000 5058000 13  -1.1777 nan
MMRF_1049_1_T   1   5058000 5102000 44  -0.3198 nan
MMRF_1049_1_T   1   5102000 5178000 76  -0.1463 nan
MMRF_1049_1_T   1   5178000 5285000 107 0.1763  nan
MMRF_1049_1_T   1   5285000 5421000 136 -0.1944 nan
MMRF_1049_1_T   1   5421000 5537000 116 0.1298  nan

Also, good luck with the dream challenge!!!

**Comment by eafyounian** [comment]
Thank you! 

Hmm... Normally, the `baf.mean` is `nan` for a segment if there is no heterozygous SNP in that segment. I would not say that this is normal. Would you please tell me which `SNP position file` you used? One explanation that comes to mind is that there were not many SNP positions for which the sample was heterozygous. 

I would also not say that there are no cnLOH regions in the sample before I have "played around" with `--clogr_thresh `and `--baf_thresh` parameters in `Segmentum find recurrent cnLOHs` command. I would loosen the parameter values a bit to get at least some hits (which might be false positives). Then I would examine those regions visually, for example in the `IGV`. To do so, I would open the `WIG` file that is by default generated for the `heterozygous SNP allele fractions` when running the `Segmentum analyze with BAF` (i.e. option  `--BAF=True`) as well as the modified `SEG` file `cut -f1,2,3,4,5,6 sample_x_t.seg > IGV_sample_x_t.seg` in the IGV and inspect the regions manually.

Hope this explanation is not too vague!

**Comment by DawnMKing** [comment]
I used the snp position provided for this tool hg19_1000g_2014oct_SNPs.tsv.gz. Also, I tried many parameter values and still nothing. Ideally, should the -clogr and baf_thresh be the same as what I used to generate the .seg file? I will look at IGV now.

**Comment by eafyounian** [comment]
This is a bit weird! Is there a possibility that you send me the results (i.e. the `SEG`, `TSV`, and the `WIG` files) so that I can take a quick look at them?

I would say those values should be good supposing that the sample purity is around `70%` (I am not sure that this would always hold true). I would try to see whether I get anything at all at the limits. Let's say  `--baf_thresh` very close to `0.5` e.g. `0.45` and  `--clogr_thresh` close to `1`.

**Comment by DawnMKing** [comment]
If I am understanding this correctly, I am looking for events with a BAF close to .5 with no copynumber changes. By the images below, chr1 which has highest baf also has copy number changes, so this is not cnLOH. In this case, by inspection, could I say that there are no cnLOH events in this sample?
![image](https://user-images.githubusercontent.com/21011198/32796697-229c7d9a-c935-11e7-9d08-59acf20d041d.png)
![image](https://user-images.githubusercontent.com/21011198/32796758-55b8d55c-c935-11e7-93d8-8a4e1aed9595.png)

**Comment by DawnMKing** [comment]
[MMRF_2087_2_T.wig.gz](https://github.com/eafyounian/Segmentum/files/1472030/MMRF_2087_2_T.wig.gz)
[MMRF_2087_1_N.wig.gz](https://github.com/eafyounian/Segmentum/files/1472031/MMRF_2087_1_N.wig.gz)
[B_allele_fraction_2.tsv.gz](https://github.com/eafyounian/Segmentum/files/1472032/B_allele_fraction_2.tsv.gz)


[MMRF_2087_2.txt](https://github.com/eafyounian/Segmentum/files/1472039/MMRF_2087_2.txt)
 Github would not accept a .seg file type, so I converted to .txt

**Comment by eafyounian** [comment]
Can you please also include the `WIG` file for the `BAF` values?

**Comment by DawnMKing** [comment]
Oops, sorry...
[MMRF_2087_2_T_BAFs.txt](https://github.com/eafyounian/Segmentum/files/1472071/MMRF_2087_2_T_BAFs.txt)

**Comment by eafyounian** [comment]
Thank you!
A quick question: In the `IGV` it seems that your data is whole exome sequencing (WES) and not whole genome sequencing (WGS). Is that right? If this is the case, it might explain the `nan` issue.

**Comment by DawnMKing** [comment]
Yes, it is WES data. I just realized that I completely glossed over that when reading about this. I should have asked before started processing if I could run this on WES data... sorry :(. I was just excited to have an easy tool to calculate cnLOH. Will it still be okay to use?

**Comment by eafyounian** [comment]
Thank you for your answer!

Unfortunately, Segmentum is originally developed for `WGS` data which makes it not suitable for `WES` data. That being said, you might still want to experiment by increasing the `window size` (maybe from `11` to `100` or even `200`) and may be even decreasing the `clogr_threshold` a little bit and see whether you get any signal. But this way, I imagine that the resolution would be greatly diminished. 

If you decide that you want to give it a try, you only need to rerun `Segmentum analyze with BAF` and subsequent `Segmentum find recurrent cnLOHs`. Please let me know if this approach works. 

Please feel free to ask if you have further question.

**Comment by eafyounian** [comment]
> I am looking for events with a BAF close to .5 with no copynumber changes. By the images below, chr1 which has highest baf also has copy number changes, so this is not cnLOH. In this case, by inspection, could I say that there are no cnLOH events in this sample?

Yes, you are right! One note though: the `WIG` file for the `BAF` values has the mirrored BAF value around the baseline (i.e. `0.5`) and that is why here we are looking for values close to `0.5`.

**Comment by DawnMKing** [comment]
Increasing window size did not help, I got a lot of Detected no breakpoints. Suck that I need to find something else for WES data, any hopes in the future to extend?

I will definitely use this when I get to WGS that I have for these samples, especially since I have a handle on this tool :). I will let you know if there are issues with WGS data, but I imagine all will be good once I am using the correct dataset :).

Thanks for all your help and good luck with the dream challange!

**Comment by eafyounian** [comment]
Thank you for the information! That is a pity that it did not work!

I would love to extend it to support `WES` but unfortunately, at the moment, I am busy with few other projects (If I get some grant and free time I would most probably do it).

Glad to hear that you are considering to use this tool in the future. Please feel free to ask if you have further questions.

Thank you again!
